[project]
name = "task-manager"
version = "0.1.0"
description = "CLI Task Manager Capstone - Phase 4"
authors = [
    { name = "Aahish" }
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
